version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run:
          name: 'Version check'
          command: |
            node --version
            yarn --version
      - checkout
      - run:
          name: 'Dependencies'
          command: yarn install --frozen-lockfile
      - run:
          name: 'Monorepo setup'
          command: yarn run bootstrap
      - run:
          name: 'Lint'
          command: yarn run quality:lint
      - run:
          name: 'Build'
          command: yarn run build:release
      - run:
          name: 'Unit tests'
          command: yarn run test:coverage
